### DISCUSSION TITLE
Github actions for testing

### DISCUSSION THREAD

**Discussion by MalteBoehm** [fzyzcjy/flutter_convenient_test#225] [Show and tell]
Hey there, how would you run flutter_convenient_test via GitHub actions? 

This is how i run my stuff so far

```yaml
name: Run all tests
on: [ push, workflow_dispatch, pull_request ]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
```
