### DISCUSSION TITLE
Running it on the CI

### DISCUSSION THREAD

**Discussion by Rohithgilla12** [fzyzcjy/flutter_convenient_test#311] [Q&A]
Hey I saw this multiple times on how to run on the CI

https://github.com/fzyzcjy/flutter_convenient_test/discussions/254#discussioncomment-3414090

Considering this is a github action file.
```yaml
      - uses: actions/checkout@v2
        with: 
          repository: "fzyzcjy/flutter_convenient_test"
          path: 'manager'

      - name: Run manager
        run: dart pub get && cd bin && dart run convenient_test_manager_dart.dart &
        working-directory: ./manager/packages/convenient_test_manager_dart/

      - name: Run integration tests
        run: flutter run integration_test/main_test.dart --host-vmservice-port 9753 --disable-service-auth-codes  --dart-define CONVENIENT_TEST_APP_CODE_DIR=lib/  

```

Or is there any other or better way for running this in the CI 😄 

This is kind of how the output of the `Run integration tests` looks like and it doesn't work :( 
It's stuck there for quite a long time until I decide to cancel the workflow.

![image](https://user-images.githubusercontent.com/19389850/213479424-95120a66-cf0d-4657-9def-6b62e2f8775a.png)

Really appreciate your help @fzyzcjy !!
