### ISSUE TITLE
test_api version conflict

### ISSUE THREAD

**Issue by lthoedt** [fzyzcjy/flutter_convenient_test#340]
**Describe the bug**
I cannot add convenient_test_dev to the dependencies because the test_api versions wont match up.

**To Reproduce**
```
flutter pub add dev:convenient_test_dev
```
It says: 
```
Because every version of convenient_test_dev depends on test_api ^0.4.2 and every version of flutter_test from sdk depends on test_api 0.5.1, convenient_test_dev is incompatible with flutter_test from sdk.
So, because otomo depends on both flutter_test from sdk and convenient_test_dev ^1.2.1, version solving failed.
```
These are my dependencies:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  convenient_test_dev: ^1.2.1
```

removing flutter_test doesnt help either.

Is this caused by me using the latest version of flutter?

**Comment by fzyzcjy** [comment]
Looks like this is conflict with flutter version itself. Which flutter are you using?

**Comment by lthoedt** [comment]
The latest stable: `3.10.3`

**Comment by fzyzcjy** [comment]
Oh I see the problem: Please use the master branch since I have not https://github.com/fzyzcjy/flutter_convenient_test/issues/341

**Comment by lthoedt** [comment]
Thanks for responding! But as I expected; upgrading to a newer flutter version is not doing anything.
```
Because every version of convenient_test_dev depends on test_api ^0.4.2 and every version of flutter_test from sdk depends on test_api 0.6.0, convenient_test_dev is incompatible with flutter_test from sdk.
So, because otomo depends on both flutter_test from sdk and convenient_test_dev ^1.2.1, version solving failed.
exit code 1
``` I still get this message. Kind of stupid but i guess backwards compatibility is not a concern of `test_api`.

**Comment by fzyzcjy** [comment]
Maybe try to update to master branch of *this repo*, instead of *flutter itself*?

**Comment by lthoedt** [comment]
How do i do that? How would i then import the packages. Because you released 1.2.1, is there a later version on master?

**Comment by fzyzcjy** [comment]
https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter

**Comment by lthoedt** [comment]
Wow, i didnt know that that was possible. Im starting to feel dumb but it still wont work.
I tried from git and hosted both fail. 
```yaml
convenient_test:
    git:
      url: https://github.com/fzyzcjy/flutter_convenient_test.git
      path: packages/convenient_test/
      ref: master # branch name
  # convenient_test:
  #   hosted:
  #     url: https://github.com/fzyzcjy/flutter_convenient_test/tree/master/packages/convenient_test
  #     version: 1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  convenient_test_dev:
    git:
      url: https://github.com/fzyzcjy/flutter_convenient_test.git
      path: packages/convenient_test_dev/
      ref: master # branch name
  # convenient_test_dev:
  #   hosted:
  #     url: https://github.com/fzyzcjy/flutter_convenient_test/tree/master/packages/convenient_test_dev
  #     version: 1.2.1
```
This is the error for git:
```
Because every version of convenient_test_dev from git depends on convenient_test from hosted and otomo depends on
  convenient_test from git, convenient_test_dev from git is forbidden.
So, because otomo depends on convenient_test_dev from git, version solving failed.
```
Using hosted, the packages cannot be found. Or should i clone the repo and do it that way?
