### ISSUE TITLE
test_api version conflict

### ISSUE THREAD

**Issue by lthoedt** [fzyzcjy/flutter_convenient_test#345]
**Describe the bug**
The manager cannot seem to be build since there are version conflicts with test_api. This issue was around a couple weeks ago and still does not seem to be fixed.

**To Reproduce**
Build manager.

**Expected behavior**
Builds

Command output:
```cmd
[packages\convenient_test_manager] flutter pub get
Resolving dependencies...
Note: test_api is pinned to version 0.6.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because convenient_test_manager depends on flutter_test from sdk which depends on test_api 0.6.0, test_api 0.6.0 is required.
So, because convenient_test_manager depends on test_api ^0.5.1, version solving failed.
exit code 1
```

My pubspec.yaml, straight from this repo.

```yaml
name: convenient_test_manager
description: Write and debug tests easily, with full action history, time travel, screenshots, rapid re-execution, video records, interactivity, isolation and more

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0

environment:
  # sdk: ">=2.17.0 <=3.0.0"
  sdk: '^3.0.0'
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  convenient_test_common: ^1.0.0
  convenient_test_common_dart: ^1.0.0
  convenient_test_dev: ^1.0.0
  convenient_test_manager_dart: ^1.0.0
  cupertino_icons: ^1.0.2
  dart_vlc: ^0.2.0
  file_picker: ^4.5.1
  fixnum: ^1.0.0
  flutter:
    sdk: flutter
  flutter_mobx:
    git:
      url: https://github.com/fzyzcjy/mobx.dart
      ref: 2e447ae595fa61d5b7a9beec6bee6c1a1155b0f5
      path: flutter_mobx
  flutter_portal: ^1.1.3
  flutter_test:
    sdk: flutter
  get_it: ^7.0.0
  git: ^2.0.0
  grpc: ^3.0.0
  intl: ^0.18.0
  mobx: ^2.0.7
  path: ^1.8.0
  path_provider: ^2.0.9
  protobuf: ^2.0.0
  scrollable_positioned_list: ^0.3.2
  test_api: ^0.5.1
  tuple: ^2.0.0 

dependency_overrides:
  convenient_test:
    path: ../convenient_test
  convenient_test_common:
    path: ../convenient_test_common
  convenient_test_common_dart:
    path: ../convenient_test_common_dart
  convenient_test_dev:
    path: ../convenient_test_dev
  convenient_test_manager_dart:
    path: ../convenient_test_manager_dart
  grpc:
    git:
      url: https://github.com/fzyzcjy/grpc-dart # #3761

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.3.0
  dart_code_metrics: ^5.5.1
  lint: ">=1.8.2 <3.0.0"
  mobx_codegen: ^2.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto_Mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700
```

My flutter:

```cmd
flutter --version
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (5 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```

I am not sure whether this is an issue on my side or the application, since i seem to be the only one reporting this it is probably me. But I feel like i have tried everything.
