### ISSUE TITLE
convenient_test_dev version conflicts with integration_test version.

### ISSUE THREAD

**Issue by sinhaaritro** [fzyzcjy/flutter_convenient_test#386]
**Describe the bug**
Failed to solve package version

When I try to run the `flutter pub get`, I get the error.
```sh
Because convenient_test_dev <1.3.0 depends on test_api ^0.4.2 and convenient_test_dev >=1.3.0 depends on test_api >=0.5.1 <0.7.0,     
  every version of convenient_test_dev requires test_api ^0.4.2 or >=0.5.1 <0.7.0.
And because every version of integration_test from sdk depends on test_api 0.7.0, integration_test from sdk is incompatible with      
  convenient_test_dev.
So, because testapp depends on both integration_test from sdk and convenient_test_dev any, version solving failed.
```

My `pubspec.yaml`
```yaml
name: testapp
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  drift: ^2.18.0
  drift_dev: ^2.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  integration_test:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  reactive_forms: ^17.0.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shared_preferences_tools: ^1.0.3
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.22
  convenient_test: any

dev_dependencies:
  build_runner: ^2.4.10
  convenient_test_dev: any
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  generate: true
  uses-material-design: true
```

My flutter version is
```sh
C:\Users\Aritro>flutter --version
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (7 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```

**Desktop (please complete the following information):**
 - OS: Windows 10
